server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: msa-spring-cloud-gateway-test

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG

#cloud:
#  gateway:
#    routes:
#      - id: user
#        uri: lb://MSA-USER-API-TEST
#        predicates:
#          - Path=/api/v1/auth/**
#      - id : board
#        uri : lb://MSA-BOARD-API-TEST
#        predicates:
#          - Path=/api/v1/board/**
#      - id: contents
#        uri : lb://MSA-CONTENTS-API-TEST
#        predicates:
#          - Path=/contents/**